<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBimmys9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBimmys9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBimmys9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBimmys9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBimmys9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Bimmys9',
    'container.build_id' => 'b64f5999',
    'container.build_time' => 1642173692,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBimmys9');
