<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrExvYe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrExvYe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrExvYe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrExvYe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLrExvYe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LrExvYe',
    'container.build_id' => 'b0483c7c',
    'container.build_time' => 1642423155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrExvYe');
