## USERS
userLogin:
    path: /security/users/login
    controller: App\Controller\UserController::login
    methods: ["POST"]

userGetAll:
    path: /security/users
    controller: App\Controller\UserController::getAll
    methods: ["GET"]

userGetOne:
    path: /security/users/{id}
    controller: App\Controller\UserController::getOne
    methods: ["GET"]
    requirements:
        id: '\d+'

## ARTICLES

articleGetAll:
    path: /edition/articles
    controller: App\Controller\ArticleController::getAll
    methods: ["GET"]

articleGetOne:
    path: /edition/articles/{id}
    controller: App\Controller\ArticleController::getOne
    methods: ["GET"]
    requirements:
        id: '\d+'

articleUpdateOne:
    path: /edition/articles/{id}
    controller: App\Controller\ArticleController::updateOne
    methods: ["PUT"]
    requirements:
        id: '\d+'

articleGetByLang:
    path: /edition/articles/{lang}
    controller: App\Controller\ArticleController::getAllByLang
    methods: ["GET"]

articleNew:
    path: /edition/articles
    controller: App\Controller\ArticleController::save
    methods: ["POST"]


## MAIL

mailGetAll:
    path: /mails
    controller: App\Controller\MailController::getAll
    methods: ["GET"]

mailGetOne:
    path: /mails/{id}
    controller: App\Controller\MailController::getOne
    methods: ["GET"]
    requirements:
        id: '\d+'

mailSendOne:
    path: /mails
    controller: App\Controller\MailController::sendOneMail
    methods: ["POST"]


## PICTURES

PictureGetAllByEntities:
    path: /{entity}/pictures/{ref}
    controller: App\Controller\PictureController::getAllByEntity
    methods: ["GET"]

PictureGetOne:
    path: /pictures/{id}
    controller: App\Controller\PictureController::getOne
    methods: ["GET"]

PictureAddOne:
    path: /pictures
    controller: App\Controller\PictureController::save
    methods: ["POST"]
