
##User Login
special_user_login:
    path: /security/users/login
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::login
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: loginSpecial

##User Register
special_user_register:
    path: /security/users/register
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::register
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: registerSpecial

##User Activation
special_user_activation:
    path: /security/users/activation
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::activation
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: activationSpecial

##User Re-Activation
special_user_reactivation:
    path: /security/users/reactivation
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::reactivation
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: reactivationSpecial

##User ForgotPassword
special_user_forgotpassword:
    path: /security/users/forgotpassword
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::forgotpassword
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: forgotpasswordSpecial

##User ResetPassword
special_user_resetpassword:
    path: /security/users/resetpassword
    methods: ["POST"]
    defaults:
        _controller: App\Controller\UserController::resetpassword
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: resetpasswordSpecial

##IPN Notification
ipn_notification_special:
    path: /ipn/notif
    methods: ["POST"]
    defaults:
        _controller: App\Controller\NotificationController::notification
        _api_resource_class: App\Entity\IpnData
        _api_collection_operation_name: notifSpecial

##IPN Notification TEST
ipn_notification_special_test:
    path: /ipn/notif/test
    methods: ["POST"]
    defaults:
        _controller: App\Controller\NotificationController::notificationTest
        _api_resource_class: App\Entity\IpnData
        _api_collection_operation_name: notifSpecialTest

ipn_raw:
    path: /transactions/{id}/callback
    controller: App\Controller\NotificationController::notificationRawData


##Transactions By Users
user_transaction:
    path: /users/{id}/transactions
    controller: App\Controller\UserController::usertransactions


##Picture
hotel_picture:
    path: /{entity}/{id}/image
    controller: App\Controller\PictureController::hotelImage

##BOOKING
room_by_hotel:
    path: /hotel/{id}/rooms
    controller: App\Controller\HotelController::roomsByHotel

free_rooms:
    path: /booking/free
    controller: App\Controller\HotelController::freeRooms

booked_rooms:
    path: /booking/booked
    controller: App\Controller\HotelController::bookedRooms

free_rooms_by_hotel:
    path: /booking/{hotelId}/free
    controller: App\Controller\HotelController::freeRoomsByHotel
    requirements:
        hotelId: '\d+'

room_booking:
    path: /rooms/{id}/booking
    methods: ["POST"]
    controller: App\Controller\HotelController::roomsBooking

booking:
    path: /booking
    controller: App\Controller\HotelController::booking

bookingByUser:
    path: /booking/{userId}
    controller: App\Controller\HotelController::bookingByUser
    requirements:
        userId: '\d+'

bookingCancel:
    path: /booking/{id}/cancel
    controller: App\Controller\HotelController::bookingCancel
    methods: ["PUT"]
